/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */


#ifndef _UAPI_KBASE_GPU_REGMAP_CSF_H_
#define _UAPI_KBASE_GPU_REGMAP_CSF_H_

#include <linux/types.h>

#if !MALI_USE_CSF && defined(__KERNEL__)
#error "Cannot be compiled with JM"
#endif



#define IPA_CONTROL_BASE       0x40000
#define IPA_CONTROL_REG(r)     (IPA_CONTROL_BASE+(r))
#define COMMAND                0x000 
#define STATUS                 0x004 
#define TIMER                  0x008 

#define SELECT_CSHW_LO         0x010 
#define SELECT_CSHW_HI         0x014 
#define SELECT_MEMSYS_LO       0x018 
#define SELECT_MEMSYS_HI       0x01C 
#define SELECT_TILER_LO        0x020 
#define SELECT_TILER_HI        0x024 
#define SELECT_SHADER_LO       0x028 
#define SELECT_SHADER_HI       0x02C 


#define VALUE_CSHW_BASE        0x100
#define VALUE_CSHW_REG_LO(n)   (VALUE_CSHW_BASE + ((n) << 3))       
#define VALUE_CSHW_REG_HI(n)   (VALUE_CSHW_BASE + ((n) << 3) + 4)   


#define VALUE_MEMSYS_BASE      0x140
#define VALUE_MEMSYS_REG_LO(n) (VALUE_MEMSYS_BASE + ((n) << 3))     
#define VALUE_MEMSYS_REG_HI(n) (VALUE_MEMSYS_BASE + ((n) << 3) + 4) 

#define VALUE_TILER_BASE       0x180
#define VALUE_TILER_REG_LO(n)  (VALUE_TILER_BASE + ((n) << 3))      
#define VALUE_TILER_REG_HI(n)  (VALUE_TILER_BASE + ((n) << 3) + 4)  

#define VALUE_SHADER_BASE      0x1C0
#define VALUE_SHADER_REG_LO(n) (VALUE_SHADER_BASE + ((n) << 3))     
#define VALUE_SHADER_REG_HI(n) (VALUE_SHADER_BASE + ((n) << 3) + 4) 

#include "../../csf/mali_gpu_csf_control_registers.h"


#define AS_MEMATTR_AARCH64_OUTER_IMPL_DEF 0x88ull

#define AS_MEMATTR_AARCH64_OUTER_WA       0x8Dull

#define AS_MEMATTR_AARCH64_NON_CACHEABLE  0x4Cull

#define AS_MEMATTR_AARCH64_SHARED         0x8ull


#define AS_MEMATTR_INDEX_DEFAULT               0
#define AS_MEMATTR_INDEX_DEFAULT_ACE           3


#define AS_MEMATTR_INDEX_IMPL_DEF_CACHE_POLICY 0

#define AS_MEMATTR_INDEX_FORCE_TO_CACHE_ALL    1

#define AS_MEMATTR_INDEX_WRITE_ALLOC           2

#define AS_MEMATTR_INDEX_OUTER_IMPL_DEF        3

#define AS_MEMATTR_INDEX_OUTER_WA              4

#define AS_MEMATTR_INDEX_NON_CACHEABLE         5

#define AS_MEMATTR_INDEX_SHARED                6


#define CSF_CONFIG 0xF00


#define CSF_CONFIG_FORCE_COHERENCY_FEATURES_SHIFT 2


#define CORE_FEATURES           0x008   
#define MCU_CONTROL             0x700
#define MCU_STATUS              0x704

#define MCU_CNTRL_ENABLE        (1 << 0)
#define MCU_CNTRL_AUTO          (1 << 1)
#define MCU_CNTRL_DISABLE       (0)

#define MCU_STATUS_HALTED        (1 << 1)

#define PRFCNT_BASE_LO   0x060  
#define PRFCNT_BASE_HI   0x064  
#define PRFCNT_CONFIG    0x068  

#define PRFCNT_CSHW_EN   0x06C  

#define PRFCNT_SHADER_EN 0x070  
#define PRFCNT_TILER_EN  0x074  
#define PRFCNT_MMU_L2_EN 0x07C  


#define JOB_IRQ_GLOBAL_IF       (1 << 31)   


#define GPU_COMMAND_CODE_NOP                0x00 
#define GPU_COMMAND_CODE_RESET              0x01 
#define GPU_COMMAND_CODE_PRFCNT             0x02 
#define GPU_COMMAND_CODE_TIME               0x03 
#define GPU_COMMAND_CODE_FLUSH_CACHES       0x04 
#define GPU_COMMAND_CODE_SET_PROTECTED_MODE 0x05 
#define GPU_COMMAND_CODE_FINISH_HALT        0x06 
#define GPU_COMMAND_CODE_CLEAR_FAULT        0x07 




#define GPU_COMMAND_RESET_PAYLOAD_FAST_RESET 0x00


#define GPU_COMMAND_RESET_PAYLOAD_SOFT_RESET 0x01


#define GPU_COMMAND_RESET_PAYLOAD_HARD_RESET 0x02


#define GPU_COMMAND_PRFCNT_PAYLOAD_SAMPLE 0x01 
#define GPU_COMMAND_PRFCNT_PAYLOAD_CLEAR  0x02 


#define GPU_COMMAND_TIME_DISABLE 0x00 
#define GPU_COMMAND_TIME_ENABLE  0x01 


#define GPU_COMMAND_FLUSH_PAYLOAD_NONE             0x00 
#define GPU_COMMAND_FLUSH_PAYLOAD_CLEAN            0x01 
#define GPU_COMMAND_FLUSH_PAYLOAD_INVALIDATE       0x02 
#define GPU_COMMAND_FLUSH_PAYLOAD_CLEAN_INVALIDATE 0x03 


#define GPU_COMMAND_CODE_PAYLOAD(opcode, payload) \
	((__u32)opcode | ((__u32)payload << 8))



#define GPU_COMMAND_NOP \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_NOP, 0)


#define GPU_COMMAND_SOFT_RESET \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_RESET, GPU_COMMAND_RESET_PAYLOAD_SOFT_RESET)


#define GPU_COMMAND_HARD_RESET \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_RESET, GPU_COMMAND_RESET_PAYLOAD_HARD_RESET)


#define GPU_COMMAND_PRFCNT_CLEAR \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_PRFCNT, GPU_COMMAND_PRFCNT_PAYLOAD_CLEAR)


#define GPU_COMMAND_PRFCNT_SAMPLE \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_PRFCNT, GPU_COMMAND_PRFCNT_PAYLOAD_SAMPLE)


#define GPU_COMMAND_CYCLE_COUNT_START \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_TIME, GPU_COMMAND_TIME_ENABLE)


#define GPU_COMMAND_CYCLE_COUNT_STOP \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_TIME, GPU_COMMAND_TIME_DISABLE)


#define GPU_COMMAND_CLEAN_CACHES \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_FLUSH_CACHES, GPU_COMMAND_FLUSH_PAYLOAD_CLEAN)


#define GPU_COMMAND_CLEAN_INV_CACHES \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_FLUSH_CACHES, GPU_COMMAND_FLUSH_PAYLOAD_CLEAN_INVALIDATE)


#define GPU_COMMAND_SET_PROTECTED_MODE \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_SET_PROTECTED_MODE, 0)


#define GPU_COMMAND_FINISH_HALT \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_FINISH_HALT, 0)


#define GPU_COMMAND_CLEAR_FAULT \
	GPU_COMMAND_CODE_PAYLOAD(GPU_COMMAND_CODE_CLEAR_FAULT, 0)




#define GPU_FAULTSTATUS_EXCEPTION_TYPE_SHIFT 0
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_MASK (0xFFul)
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_GET(reg_val) \
	(((reg_val)&GPU_FAULTSTATUS_EXCEPTION_TYPE_MASK) \
	 >> GPU_FAULTSTATUS_EXCEPTION_TYPE_SHIFT)
#define GPU_FAULTSTATUS_ACCESS_TYPE_SHIFT 8
#define GPU_FAULTSTATUS_ACCESS_TYPE_MASK \
	(0x3ul << GPU_FAULTSTATUS_ACCESS_TYPE_SHIFT)

#define GPU_FAULTSTATUS_ADDR_VALID_SHIFT 10
#define GPU_FAULTSTATUS_ADDR_VALID_FLAG \
	(1ul << GPU_FAULTSTATUS_ADDR_VALID_SHIFT)

#define GPU_FAULTSTATUS_JASID_VALID_SHIFT 11
#define GPU_FAULTSTATUS_JASID_VALID_FLAG \
	(1ul << GPU_FAULTSTATUS_JASID_VALID_SHIFT)

#define GPU_FAULTSTATUS_JASID_SHIFT 12
#define GPU_FAULTSTATUS_JASID_MASK (0xF << GPU_FAULTSTATUS_JASID_SHIFT)
#define GPU_FAULTSTATUS_JASID_GET(reg_val) \
	(((reg_val)&GPU_FAULTSTATUS_JASID_MASK) >> GPU_FAULTSTATUS_JASID_SHIFT)
#define GPU_FAULTSTATUS_JASID_SET(reg_val, value) \
	(((reg_val) & ~GPU_FAULTSTATUS_JASID_MASK) |  \
	(((value) << GPU_FAULTSTATUS_JASID_SHIFT) & GPU_FAULTSTATUS_JASID_MASK))

#define GPU_FAULTSTATUS_SOURCE_ID_SHIFT 16
#define GPU_FAULTSTATUS_SOURCE_ID_MASK \
	(0xFFFFul << GPU_FAULTSTATUS_SOURCE_ID_SHIFT)



#define GPU_FAULTSTATUS_ACCESS_TYPE_ATOMIC 0x0
#define GPU_FAULTSTATUS_ACCESS_TYPE_EXECUTE 0x1
#define GPU_FAULTSTATUS_ACCESS_TYPE_READ 0x2
#define GPU_FAULTSTATUS_ACCESS_TYPE_WRITE 0x3



#define GPU_EXCEPTION_TYPE_SW_FAULT_0 ((__u8)0x70)
#define GPU_EXCEPTION_TYPE_SW_FAULT_1 ((__u8)0x71)
#define GPU_EXCEPTION_TYPE_SW_FAULT_2 ((__u8)0x72)


#define GPU_FAULTSTATUS_EXCEPTION_TYPE_OK 0x00
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_GPU_BUS_FAULT 0x80
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_GPU_SHAREABILITY_FAULT 0x88
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_SYSTEM_SHAREABILITY_FAULT 0x89
#define GPU_FAULTSTATUS_EXCEPTION_TYPE_GPU_CACHEABILITY_FAULT 0x8A


#define GPU_FAULTSTATUS_ADDRESS_VALID_SHIFT GPU_U(10)
#define GPU_FAULTSTATUS_ADDRESS_VALID_MASK (GPU_U(0x1) << GPU_FAULTSTATUS_ADDRESS_VALID_SHIFT)
#define GPU_FAULTSTATUS_ADDRESS_VALID_GET(reg_val) \
	(((reg_val)&GPU_FAULTSTATUS_ADDRESS_VALID_MASK) >> GPU_FAULTSTATUS_ADDRESS_VALID_SHIFT)
#define GPU_FAULTSTATUS_ADDRESS_VALID_SET(reg_val, value) \
	(((reg_val) & ~GPU_FAULTSTATUS_ADDRESS_VALID_MASK) |  \
	(((value) << GPU_FAULTSTATUS_ADDRESS_VALID_SHIFT) & GPU_FAULTSTATUS_ADDRESS_VALID_MASK))


#define GPU_FAULT               (1 << 0)    
#define GPU_PROTECTED_FAULT     (1 << 1)    
#define RESET_COMPLETED         (1 << 8)    
#define POWER_CHANGED_SINGLE    (1 << 9)    
#define POWER_CHANGED_ALL       (1 << 10)   
#define CLEAN_CACHES_COMPLETED  (1 << 17)   
#define DOORBELL_MIRROR         (1 << 18)   
#define MCU_STATUS_GPU_IRQ      (1 << 19)   


#define GPU_IRQ_REG_COMMON (GPU_FAULT | GPU_PROTECTED_FAULT | RESET_COMPLETED \
			| POWER_CHANGED_ALL | MCU_STATUS_GPU_IRQ)


#define PRFCNT_SAMPLE_COMPLETED (1 << 16)   

#endif 
