

#ifndef _LINUX_ANDROID_AID_H
#define _LINUX_ANDROID_AID_H


#define AID_OBSOLETE_000 KGIDT_INIT(3001)  
#define AID_OBSOLETE_001 KGIDT_INIT(3002)  
#define AID_INET         KGIDT_INIT(3003)
#define AID_NET_RAW      KGIDT_INIT(3004)
#define AID_NET_ADMIN    KGIDT_INIT(3005)
#define AID_NET_BW_STATS KGIDT_INIT(3006)  
#define AID_NET_BW_ACCT  KGIDT_INIT(3007)  

#endif
