

#ifndef _LINUX_TIMERFD_H
#define _LINUX_TIMERFD_H


#include <linux/fcntl.h>


#include <linux/ioctl.h>


#define TFD_TIMER_ABSTIME (1 << 0)
#define TFD_TIMER_CANCEL_ON_SET (1 << 1)
#define TFD_CLOEXEC O_CLOEXEC
#define TFD_NONBLOCK O_NONBLOCK

#define TFD_SHARED_FCNTL_FLAGS (TFD_CLOEXEC | TFD_NONBLOCK)

#define TFD_CREATE_FLAGS TFD_SHARED_FCNTL_FLAGS

#define TFD_SETTIME_FLAGS (TFD_TIMER_ABSTIME | TFD_TIMER_CANCEL_ON_SET)

#define TFD_IOC_SET_TICKS	_IOW('T', 0, u64)

#endif 
