

#ifndef __VIDEO_VIDEONODE_H
#define __VIDEO_VIDEONODE_H __FILE__

#define EXYNOS_VIDEONODE_MFC_DEC		6
#define EXYNOS_VIDEONODE_MFC_ENC		7
#define EXYNOS_VIDEONODE_MFC_DEC_DRM		8
#define EXYNOS_VIDEONODE_MFC_ENC_DRM		9
#define EXYNOS_VIDEONODE_MFC_ENC_OTF		10
#define EXYNOS_VIDEONODE_MFC_ENC_OTF_DRM	11


#define EXYNOS_VIDEONODE_SCALER(x)		(50 + x)


#define EXYNOS_VIDEONODE_FIMC_IS		(100)

#endif 
